# Generated by Django 5.2.5 on 2025-08-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='unknown',
            field=models.CharField(default='test', max_length=10),
        ),
    ]
