# Generated by Django 5.2.5 on 2025-08-10 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_album_article_alter_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='band',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='music.band'),
            preserve_default=False,
        ),
    ]
