# Generated by Django 5.2.5 on 2025-08-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='articles', to='music.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='article',
            field=models.ManyToManyField(to='music.article'),
        ),
    ]
