# Generated by Django 5.2.5 on 2025-08-10 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_article_categories_category_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='article',
        ),
    ]
