# Generated by Django 5.2.5 on 2025-08-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_remove_category_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(to='music.category'),
        ),
    ]
